Hardwares:
   Shield:
      port: COM4 
      telephone: 763476473643376437
   TTOpen:
      port: COM4 
      telephone: 87387438743
IDEs:
   1_0_x:
      Path: C:\Program Files (x86)\Arduino\
   1_5_x:
      Path: D:\TT\arduino-1.5.8
Sketchs:
   Substitutions:
      GPRS_APN: telefonica.com
      login: un_login
      password: una password