Hardwares:
   Shield:
      port: COM5 
      timeout: 30
   TTOpen:
      port: COM4 
      timeout: 10
IDEs:
   1_0_x:
      Path: C:\PROGRA~2\Arduino
   1_5_x:
      Path: D:\TT\arduino-1.5.8
Sketchs:
   Substitutions:
      GPRS_APN: telefonica.com
      login: un_login
      password: una password
      tosendphone: '+34646237397'