Hardwares:
   Shield: 
      telephone: 763476473643376437
   TTOpen:
      telephone: 87387438743
IDEs:
   1.0.x:
      Path: /kjskjdksj/kjskjds
   1.5.x:
      Path: /jhghsdjhsjhds
Sketchs:
   Substitutions:
      GPRS_APN: telefonica.com
      login: un_login
      password: una password